{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: qiime2
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - pyyaml
    - decorator
    - pandas
    - tzlocal
    - python-dateutil
    - bibtexparser
    # HACK: temporarily pin this to prevent broken build from showing up
    - future 0.16.0 py35_0

test:
  imports:
    - qiime2

  commands:
    # TODO don't require devs to remember setting this env var before running
    # tests. The value can be anything.
    - QIIMETEST= python -c "import qiime2.plugins.dummy_plugin"

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
